services:
  # API Service (Node.js with GraphQL)
  api:
    image: node:22-alpine
    container_name: weather-api
    env_file:
      - ./api/.env
    ports:
      - "${BACKEND_PORT}:4000"
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm run start"

  # Frontend Service (React Router)
  app:
    image: node:22-alpine
    container_name: weather-app
    env_file:
      - ./app/.env
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    depends_on:
      - api
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm run start"